stages:
  - run

run-notebook-dev:
  stage: run
  image: python:3.8
  tags:
    - self-hosted
  script:
    - echo "Installing Jupyter dependencies..."
    - python -m pip install --upgrade pip
    - pip install jupyter
    - echo "Executing Jupyter Notebook..."
    - jupyter nbconvert --execute --to notebook --inplace notebooks/demo-pipeline.ipynb
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      changes:
        - notebooks/**/*

run-python-dev:
  stage: run
  image: python:3.8
  tags:
    - self-hosted
  script:
    - echo "Installing Python script dependencies..."
    - python -m pip install --upgrade pip
    - pip install pandas numpy kfp~=1.8.14 scikit-learn
    - echo "Executing Python submission script..."
    - python src/submit_run.py
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
      changes:
        - src/**/*